# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-01 08:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 8, 26, 56, 637283, tzinfo=utc), verbose_name='date published'),
        ),
    ]
